# Generated by Django 4.2.5 on 2024-04-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio_maker.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=portfolio_maker.tools.upload_image_path, verbose_name='image')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='introduce')),
                ('about_me_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title of about me page')),
                ('work_experience', models.TextField(blank=True, null=True, verbose_name='experience')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('freelance', models.BooleanField(default=True, verbose_name='freelance')),
                ('Phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='website')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title')),
                ('skill_percent', models.IntegerField(default=0, verbose_name='skill percent')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_portfolios.portfolio', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='link')),
                ('image', models.ImageField(upload_to=portfolio_maker.tools.upload_image_with_rand_num_name, verbose_name='image')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_portfolios.portfolio', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
