# Generated by Django 4.2.5 on 2024-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='email'),
        ),
    ]
