# Generated by Django 4.2.5 on 2024-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolios', '0002_alter_portfolio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_skill_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Your Skill Title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='freelance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='freelance'),
        ),
    ]
