# Generated by Django 4.2.5 on 2024-04-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolios', '0003_portfolio_instagram_portfolio_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
    ]
